<?php require __DIR__ . '/../header.phtml' ?>

<script src="/admin/js/event/edit.js"></script>

<h1>アカウント編集</h1>

<p class="error" style="color: #FF0000;"></p>

<form method="POST">
    <input type="hidden" name="id" class="" value="<?= $defaults['id'] ?>">
    <div class="form-group">
        <p>
            <input type="text" name="email" class="" value="<?= $defaults['email'] ?>" placeholder="申請者メールアドレス">
        </p>
        <p>
            <input type="text" name="user_id" class="" value="<?= $defaults['user_id'] ?>" placeholder="ユーザID">
        </p>
        <p>
            <input type="text" name="password" class="" value="<?= $defaults['password'] ?>" placeholder="パスワード">
        </p>
        <p>
            <input type="text" name="held_at" class="" value="<?= $defaults['held_at'] ?>" placeholder="上映日時">
        </p>
        <p>
            <input type="text" name="place" class="" value="<?= $defaults['place'] ?>" placeholder="上映場所">
        </p>
        <p>
            <textarea type="text" name="remarks" class="" placeholder="備考"><?= $defaults['remarks'] ?></textarea>
        </p>
        <p>
            <button type="submit" class="">登録</button>
        <p>
    </div>
</form>

<?php require __DIR__ . '/../footer.phtml' ?>