<?php require __DIR__ . '/../header.phtml' ?>

<script src="/admin/js/event/edit.js"></script>

<h1 class="page-header"><?= ($defaults['id']) ? "{$defaults['user_id']}のアカウント編集" : 'アカウント追加' ?></h1>

<p class="error" style="color: #FF0000;"></p>

<form method="POST">
    <input type="hidden" name="id" class="" value="<?= $defaults['id'] ?>">
    <input type="hidden" name="held_from" class="" value="<?= $defaults['held_from'] ?>:00">
    <input type="hidden" name="held_to" class="" value="<?= $defaults['held_to'] ?>:00">
    <div class="form-group">
        <p>
            <input type="text" name="email" class="form-control" value="<?= $defaults['email'] ?>" placeholder="申請者メールアドレス">
        </p>
        <p>
            <input type="text" name="user_id" class="form-control" value="<?= $defaults['user_id'] ?>" placeholder="ユーザID">
        </p>
        <p>
            <input type="text" name="password" class="form-control" value="<?= $defaults['password'] ?>" placeholder="パスワード">
        </p>
        <p>
            <input type="text" name="held" class="form-control" value="" placeholder="上映日時">
        </p>
        <p>
            <input type="text" name="place" class="form-control" value="<?= $defaults['place'] ?>" placeholder="上映場所">
        </p>
        <p>
            <textarea type="text" name="remarks" class="form-control" placeholder="備考"><?= $defaults['remarks'] ?></textarea>
        </p>
        <p>
            <button type="submit" class="btn btn-primary">登録</button>
        <p>
    </div>
</form>

<?php require __DIR__ . '/../footer.phtml' ?>