<?php require __DIR__ . '/../header.phtml' ?>

<script src="/admin/js/event/index.js"></script>

<h1 class="page-header">上映会一覧</h1>

<table class="table table-striped">
<tbody>
<tr>
    <th>ユーザID</th>
    <th>アップロード</th>
    <th>上映場所</th>
    <th>各種機能</th>
</tr>
<?php foreach ($events as $event) { ?>
<tr>
    <td><a href="<?= $this->url->get(['for' => 'eventEdit', 'id' => $event['id']]) ?>"><?= $event['user_id'] ?></a></td>
    <td class="media_detail">
    <?= \Aass\Backend\Models\Media::status2string($event['media_status']) ?>
    <?php if ($event['media_status'] == \Aass\Backend\Models\Media::STATUS_ENCODED) { ?>
    <?= $event['media_job_end_at'] ?><br>
    <?= $event['media_uploaded_by'] ?>
    <?php } ?>
    </td>
    <td><?= $event['place'] ?></td>
    <td>
        <input type="hidden" name="id" value="<?= $event['id'] ?>">
        <input type="hidden" name="application_id" value="<?= $event['application_id'] ?>">
        <input type="hidden" name="media_id" value="<?= $event['media_id'] ?>">

        <a href="<?= $this->url->get(['for' => 'eventMedias', 'id' => $event['id']]) ?>">動画一覧</a>
        <span class="application_status">
        <?php if ($event['application_id']) { ?>
        <?php if ($event['application_status'] == \Aass\Backend\Models\Application::STATUS_CREATED) { ?>
        <a href="javascript:void(0)" class="reject_application">承認しない</a>
        <a href="javascript:void(0)" class="accept_application">承認する</a>
        <?php } else { ?>
        <?= \Aass\Backend\Models\Application::status2string($event['application_status']) ?>
        <?php } ?>
        <?php } else { ?>動画待ち
        <?php } ?>
        </span>

        <?php if ($event['application_id']) { ?>
        <a href="" target="_blank" class="download_application">ダウンロード</a>
        <?php } else { ?>
        <?php } ?>


        <?php if ($event['application_id']) { ?>
<!--         <a href="javascript:void(0)" class="delete_media">予約情報確認</a> -->
        <a href="javascript:void(0)" class="delete_application">予約削除</a>
        <?php } else { ?>
        <?php } ?>

    </td>
</tr>

<?php }?>
</tbody>
</table>

<?php require __DIR__ . '/../footer.phtml' ?>