<?php require __DIR__ . '/../header.phtml' ?>

<h1><?= $event['user_id'] ?>さんの動画一覧</h1>

<table class="table table-striped">
<tbody>
<tr>
    <th>タイトル</th>
    <th>登録者名</th>
    <th>サイズ(byte)</th>
    <th>ステータス</th>
    <th>URL</th>
    <th>各種機能</th>
</tr>
<?php foreach ($medias as $media) { ?>
<tr>
    <td><?= $media['title'] ?></td>
    <td><?= $media['uploaded_by'] ?></td>
    <td><?= $media['size'] ?></td>
    <td><?= \Aass\Backend\Models\Media::status2string($media['status']) ?></td>
    <td><?php if ($media['url']) { ?><a target="_blank" href="http://aka.ms/azuremediaplayer?url=<?= urlencode($media['url']) ?>">ストリーミング</a><?php } ?></td>
    <td>
        <input type="hidden" name="id" value="<?= $media['id'] ?>">
        <input type="hidden" name="application_id" value="<?= ($application && $application['media_id'] == $media['id']) ? $application['id'] : '' ?>">
        <a href="<?= $this->url->get(['for' => 'mediaDownload', 'id' => $media['id']]) ?>" target="_blank" class="">ダウンロード</a>

        <span class="no_apply_media"<?php if (!$application) { ?> style="display:none;"<?php } ?>>
        <?php if ($application && $application['media_id'] == $media['id']) { ?>
        <?= \Aass\Backend\Models\Application::status2string($application['status']) ?>
        <?php } else { ?>申請不可
        <?php } ?>
        </span>
    </td>
</tr>

<?php } ?>
</tbody>
</table>

<?php require __DIR__ . '/../footer.phtml' ?>