<?php require __DIR__ . '/../header.phtml' ?>

<script src="/js/media/index.js"></script>

<h1 class="page-header">動画一覧</h1>

<table class="table table-striped">
<tbody>
<tr>
    <th>タイトル<br>作成者<br>サイズ<br>作成日時</th>
    <th>ステータス</th>
    <th>thumbnail</th>
    <th>各種機能</th>
    <th>申請関連</th>
</tr>
<?php foreach ($medias as $media) { ?>
<tr>
    <td>
    <?= $media['title'] ?><br>
    <?= $media['uploaded_by'] ?><br>
    <?= $media['size'] ?><br>
    <?= $media['created_at'] ?><br>
    </td>
    <td><?= \Aass\Frontend\Models\Media::status2string($media['status']) ?></td>
    <td><?php if ($media['url_thumbnail']) { ?><img width="100px" src="<?= $media['url_thumbnail'] ?>"><?php } ?></td>
    <td>
        <input type="hidden" name="id" value="<?= $media['id'] ?>">
        <input type="hidden" name="application_id" value="<?= ($application && $application['media_id'] == $media['id']) ? $application['id'] : '' ?>">
        <a href="<?= $this->url->get(['for' => 'mediaEdit', 'id' => $media['id']]) ?>" class="">編集</a><br>
        <a href="javascript:void(0)" class="delete_media">削除</a><br>
        <?php if ($media['url_mp4']) { ?><a target="_blank" href="<?= $media['url_mp4'] ?>">mp4 download</a><br><?php } ?>
        <?php if ($media['url_streaming']) { ?><a target="_blank" href="http://aka.ms/azuremediaplayer?url=<?= urlencode($media['url_streaming']) ?>">ストリーミング</a><br><?php } ?>
    </td>
    <td>
        <span class="no_apply_media"<?php if (!$application) { ?> style="display:none;"<?php } ?>>
        <?php if ($application && $application['media_id'] == $media['id']) { ?>
        <?= \Aass\Frontend\Models\Application::status2string($application['status']) ?>
        <?php } else { ?>申請不可<br>
        <?php } ?>
        </span>

        <span class="apply_media"<?php if ($application) { ?> style="display:none;"<?php } ?>>
        <?php if ($media['status'] == \Aass\Frontend\Models\Media::STATUS_JPEG2000_ENCODED) { ?>
        <a href="javascript:void(0)">動画申請</a><br>
        <?php } else { ?>申請不可
        <?php } ?>
        </span>
    </td>
</tr>

<?php } ?>
</tbody>
</table>

<?php require __DIR__ . '/../footer.phtml' ?>