<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>映画.comシネマ 上映システム</title>

<script type="text/javascript" src="//cdn.jsdelivr.net/jquery/2.2.2/jquery.min.js"></script>
<script type="text/javascript" src="//cdn.jsdelivr.net/momentjs/2.12.0/moment.min.js"></script>
<script type="text/javascript" src="//cdn.jsdelivr.net/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/bootstrap/3.3.6/css/bootstrap.min.css" />

<!-- Include Date Range Picker -->
<script type="text/javascript" src="//cdn.jsdelivr.net/bootstrap.daterangepicker/2.1.19/daterangepicker.js"></script>
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/bootstrap.daterangepicker/2.1.19/daterangepicker.css" />

<?php //if ($flash['info']) { ?>
<script>
// 画面上部メッセージの表示
//$(function() {
//    alertTop('<?php //echo $flash['info'] ?>', 'info');
//});
</script>
<?php //} ?>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href="/">映画.comシネマ 上映システム</a>
            </div>
            <div class="navbar-collapse collapse">
                <?php if ($this->auth->getUserId()) { ?>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="<?= $this->url->get(['for' => 'eventNew']) ?>">アカウント追加</a></li>
                    <li><a href="<?= $this->url->get(['for' => 'events']) ?>">アカウント一覧</a></li>
                    <li><a href="<?= $this->url->get(['for' => 'logout']) ?>">ログアウト</a></li>
                </ul>
                Hello <?= $this->auth->getUserId() ?>
                <?php } ?>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row">
            <div class="main">