<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>映画.comシネマ 上映システム</title>

<script src="/admin/js/jquery.js"></script>
<?php //if ($flash['info']) { ?>
<script>
// 画面上部メッセージの表示
//$(function() {
//    alertTop('<?php //echo $flash['info'] ?>', 'info');
//});
</script>
<?php //} ?>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <ul class="nav navbar-nav navbar-right">
            <li><a href="<?= $this->url->get(['for' => 'eventNew']) ?>">アカウント追加</a></li>
            <li><a href="<?= $this->url->get(['for' => 'events']) ?>">アカウント一覧</a></li>
            <li><a href="<?= $this->url->get(['for' => 'logout']) ?>">ログアウト</a></li>
        </ul>
		こんにちは <?= $this->auth->getUserId() ?>さん
    </div>

    <div class="container-fluid">
