<h1>バックエンドログイン</h1>
<form action="<?= $this->url->get(['for' => 'login']) ?>" method="post">
    <fieldset>
        <div>
            <label for="user_id">UserId</label>
            <div>
                <input type="text" name="user_id">
            </div>
        </div>
        <div>
            <label for="password">Password</label>
            <div>
                <input type="password" name="password">
            </div>
        </div>
        <div>
            <input type="submit" value="Login">
        </div>
    </fieldset>
</form>