<?php require __DIR__ . '/../header.phtml' ?>

<h1 class="page-header">バックエンドログイン</h1>
<form action="<?= $this->url->get(['for' => 'login']) ?>" method="post">
<div class="form-group">
        <p>
            <input type="text" name="user_id" class="form-control" placeholder="UserId">
        </p>
        <p>
            <input type="password" name="password" class="form-control" placeholder="Password">
        </p>
        <p>
            <input type="submit" value="Login" class="btn btn-primary">
        </p>
</div>
</form>

<?php require __DIR__ . '/../footer.phtml' ?>