<form action="/auth/login" method="post">
    <fieldset>
        <div>
            <label for="email">Username/Email</label>
            <div>
                <input type="text" name="UserId">
            </div>
        </div>
        <div>
            <label for="password">Password</label>
            <div>
                <input type="password" name="Password">
            </div>
        </div>
        <div>
            <input type="submit" value="Login">
        </div>
    </fieldset>
</form>