<?php require __DIR__ . '/../header.phtml' ?>

<h1 class="page-header">フロントエンドログイン</h1>

<p class="error" style="color: #FF0000;">
<?php foreach ($messages as $message) { ?>
<?= $message ?><br>
<?php } ?>
</p>

<form action="<?= $this->url->get(['for' => 'login']) ?>" method="post">
<div class="form-group">
	<?= $form->render('user_id', ['class' => 'form-control']) ?>
	<?= $form->render('password', ['class' => 'form-control']) ?>
    <input type="submit" value="Login" class="btn btn-primary">
</div>
</form>

<?php require __DIR__ . '/../footer.phtml' ?>